### PR TITLE
WIP: Add daemon item to fix oryp4-b backlight

### PR DESCRIPTION
**Pull request by jackpot51**
This will set the DPCD byte 0x721 to enable PWM backlight control

### CODE REVIEW

**Comment by brs17** [comment]
Seems to happen too soon and requires the service to be restarted. Once it is restarted, it's a great fix

**Comment by mmstick** [comment]
@brs17 Did report an error at boot?

**Comment by brs17** [comment]
I didn't look. I can test it again when I get a moment.

**Comment by mmstick** [comment]
@brs17 Added a commit to this branch which might fix it. It has a thread waiting in the background to wait until display-manager is active before applying the DPCD PWM fix.

**Comment by brs17** [comment]
@mmstick I am now unable to get screen backlight to work at all now.

**Comment by brs17** [comment]
Well it not working was completely my fault, need to have the right firmware so that the machine can be recognized as an `oryp4-b`.

Although I see it only works on Intel graphics, this fix does not work on NVIDIA hardware.

**Comment by mmstick** [comment]
@brs17 Try this latest commit, it will check the DPCD PWM byte every 3 seconds and re-apply it as necessary.

**Comment by brs17** [comment]
It isn't perfect (login screen on intel does not work), but it seems to work inside a user session just about all the time (and on login screen under nvidia). (one time I think it crashed or something), but since then I have been able to switch between intel and nvidia mode, suspending, locking screen, logging in and out without any crashes.

**Pull request merged**
