### PR TITLE
Flash desktops

### PR DESCRIPTION
**Pull request by jackpot51**
Add support for flashing leow8, leow9, leow9-b, leow9-w, wilp12, wilp13, and wilp14

Requires update of private firmware repo:

https://github.com/system76/firmware/pull/106

### CODE REVIEW

**Comment by brs17** [comment]
@jackpot51 Added a commit to set `flash` to `False` for the leow9-w

**Comment by brs17** [comment]
The following machines had firmware installed successfully from system76-driver
- [ ] leow8
- [ ] leow9
- [ ] leow9-b
- [ ] wilp12
- [ ] wilp13
- [ ] wilp14

**Comment by jackpot51** [comment]
The dialog probably needs to change for desktops
screenshot from 2018-09-25 14-58-45

**Comment by brs17** [comment]
I'll work on creating wording for desktops...in the meantime, we had run into an issue last week(I believe it was) where it seems like updating with the fpt.efi does not image quite properly. See private repo issue: https://github.com/system76/firmware/issues/108

**Pull request closed without merging**
