### PR TITLE
Remove `system76-wallpapers` as a dependency

### PR DESCRIPTION
**Pull request by jayschwa**
The wallpapers are fluff that are not actually a dependency for making an Ubuntu installation stable. When I installed `system76-driver`, I did not appreciate that my desktop background was automatically changed to one of these wallpapers.

### CODE REVIEW

**Comment by jayschwa** [comment]
> You would have to modify this file for the settings change to not take effect - https://github.com/pop-os/system76-driver/blob/master/debian/system76-driver.gsettings-override

Thanks for the info. I updated the branch to remove those lines from the override file.

**Comment by jackpot51** [comment]
Did you actually set your wallpaper before installing system76-driver?

**Comment by jayschwa** [comment]
Yep.

**Comment by jacobgkau** [comment]
I installed a fresh copy of Ubuntu 20.04 LTS, changed the wallpaper via Settings (to one of the non-default options included with Ubuntu), installed the System76 Driver using the steps in our [support article](https://support.system76.com/articles/system76-driver/), and rebooted. The wallpaper did not change.

Performed another fresh install of Ubuntu 20.04 LTS, this time I grabbed a wallpaper from the internet and set it using the Nautilus right-click menu -> Set As Wallpaper. After installing the System76 Driver and rebooting, the wallpaper did not change.

@jayschwa Can you confirm if you're still able to reproduce this issue on 20.04 LTS, and if so, what steps you're taking to set your wallpaper and install the driver?

**Comment by bflanagin** [comment]
Is the real problem that it changed the wallpaper automatically or that system76-driver depends on system76-wallpapers and vice-versa.

Driver

``` 
system76-driver
  Depends: <python3:any> (>= 3.6~)
    python3:i386
    python3
 |Depends: dconf-gsettings-backend
  Depends: <gsettings-backend>
    dconf-gsettings-backend
  Depends: at
  Depends: <firmware-manager-virtual>
    firmware-manager
    gnome-control-center
  Depends: gir1.2-gtk-3.0
  Depends: gir1.2-notify-0.7
  Depends: gnome-shell-extension-system76-power
  Depends: linux-system76
  ...
  Depends: system76-acpi-dkms
  Depends: system76-dkms
  Depends: system76-firmware-daemon
  Depends: system76-io-dkms
  Depends: system76-oled
  Depends: system76-power
  >> Depends: system76-wallpapers
  Depends: xbacklight
  Recommends: hidpi-daemon
  Suggests: gnome-color-manager
```
and Wallpapers 

```
system76-wallpapers
  Conflicts: system76-driver (<= 14.10.2)
  Replaces: system76-driver (<= 14.10.2)
```
Could we remove the dependency in the two offending packages: [system76-driver/debian/control](https://github.com/pop-os/system76-driver/blob/master/debian/control), and [system76-wallpapers/debian/control](https://github.com/pop-os/system76-wallpapers/blob/master/debian/control)? And then the offending line in gsettings-override?

**Comment by jacobgkau** [comment]
> Is the real problem that it changed the wallpaper automatically or that system76-driver depends on system76-wallpapers and vice-versa.

I think we want the wallpapers installed with the driver (the driver is supposed to make an Ubuntu system look exactly how our image looks when we ship with Ubuntu, at least that's what I like being able to tell customers.) I could see making it a recommends instead of a dependency so it can be removed, but it would still be installed by default.

The wallpaper shouldn't be changed automatically if it has previously been set manually, and per my testing in June, that was not happening in 20.04 LTS, although @jayschwa hasn't responded to my request for confirmation.

**Comment by jayschwa** [comment]
I don't care enough about this issue to spend time attempting reproduction on a newer version of Ubuntu. I am still of the opinion that a cosmetic wallpaper package has no business being a dependency for a driver package, but you do you.

**Comment by jacobgkau** [comment]
> I am still of the opinion that a cosmetic wallpaper package has no business being a dependency for a driver package, but you do you.

The driver package also includes a GUI application for collecting logs, which is heavily used by our support team. It doesn't just provide "drivers," per se, but a complete experience for System76 users of Ubuntu. Although with Pop!_OS now being our flagship experience, maybe it doesn't make as much sense to brand Ubuntu (that would be a wider discussion.)

If `system76-wallpapers` is moved from depends to recommends (which I think would make sense), I think the gsettings override would also need to be moved to the wallpapers package, otherwise I would expect apt to still attempt to change the default wallpaper even if `--no-install-recommends` is passed.

**Comment by jacobgkau** [comment]
Thank you for bringing this concern to our attention. I'm closing this PR in favor of https://github.com/pop-os/system76-driver/pull/188 and https://github.com/pop-os/system76-wallpapers/pull/2, which will move `system76-wallpapers` to recommends (so it can be avoided with `--no-install-recommends` or removed manually after installation.)

**Pull request closed without merging**
