### PR TITLE
Use Linux 5.0 or newer to support Ryzen 3xxx

### PR DESCRIPTION
**Pull request by jackpot51**
This will fix the issues with graphics on Ryzen 3xxx, but will also potentially introduce issues on the gaze14 and with Steam until we have a patched version of linux-generic-hwe-18.04-edge.

### CODE REVIEW

**Comment by brs17** [comment]
Can confirm combo-jack does not work with kernel update.

**Comment by brs17** [comment]
Steam issue does not seem to be an issue with this kernel.

**Comment by jackpot51** [comment]
Kernels for bionic and disco are updated in proposed, ready for testing

**Comment by jackpot51** [comment]
Make sure to test gaze14 and addw1 audio

**Comment by brs17** [comment]
No regressions found on the gaze14 nor addw1 in 18.04. The kernel patch resolves display issues with integrated graphics on thelio-r1.

**Comment by brs17** [comment]
No regressions found in 19.04 either.

**Pull request merged**
