### PR TITLE
Bluetooth suspend workaround

### PR DESCRIPTION
**Pull request by n3m0-22**
Updates https://github.com/pop-os/system76-driver/pull/242 with the new fixes from https://github.com/pop-os/default-settings/pull/145 for Ubuntu.

Co-authored-by: Peter Bui [pbui@github.bx612.space](mailto:pbui@github.bx612.space)

### CODE REVIEW

**Comment by linuxgnuru** [comment]
When suspending, I'm getting the following error in the journal logs:
```
Jul 01 13:06:09 pop-os [1133]: /usr/lib/systemd/system-sleep/pop-default-settings_bluetooth-suspend failed with exit status 1.
```
Is this an actual error or is it safe to ignore?

**Comment by linuxgnuru** [comment]
On thelio-mira-b3 with nvidia 2080 with ubuntu 22.04 suspend / resume worked fine.

**Review by 13r0ck — CHANGES_REQUESTED** [review]
Please add

`
Co-authored-by: Peter Bui <pbui@bx612.space>
`

As a separate line at the end of your commit message
https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

**Review by 13r0ck — APPROVED** [review]
I force pushed an commit that makes the co-author correct

**Review by linuxgnuru — APPROVED** [review]

**Pull request merged**
