### PR TITLE
Add addw3, bonw15, and serw13 to thunderbolt reload

### PR DESCRIPTION
**Pull request by jackpot51**
This may improve thunderbolt capabilities.

### CODE REVIEW

**Comment by XV-02** [comment]
This is looking good for addw3. 

On serw13, I'm seeing some progress. I can suspend and resume, and upon resume I/O is passed successfully over the thunderbolt connection. However, on at least the 4tb crucial drive I'm currently testing with, I get errors regarding input/output from the drive - that is, the drive is in read-only mode. I'm going to set the system up to get the same failure, and see if I can pull any kind of logs for it.

I haven't got hands-on with bonw15 at all yet.

**Comment by jackpot51** [comment]
@XV-02 which slot if the crucial drive in? The output of `lspci -vt` will tell me

**Comment by XV-02** [comment]
[lspci-vt.txt](https://github.com/pop-os/system76-driver/files/11255475/lspci-vt.txt)

**Comment by jackpot51** [comment]
The correct suspend/resume flow has been implemented in firmware, make sure to remove this branch.

**Pull request closed without merging**
