### PR TITLE
Thelio Io firmware update support

### PR DESCRIPTION
**Pull request by jackpot51**
This is based on desktop-flash, which also contains numerous fixes for firmware updates. It should be merged before this: #111 

This requires a number of items currently in `thelio-io` staging branch. See https://github.com/pop-os/system76-firmware/pull/12

### CODE REVIEW

**Comment by mmstick** [comment]
Seeing this runtime error on startup with the `thelio-major-b1`

```
# sudo system76-firmware-pkexec
2019-06-10 11:51:45,402  INFO  No new firmware to install.

(system76-firmware-dialog:7617): Gtk-WARNING **: 11:51:45.509: Theme parsing error: gtk.css:4421:24: 'rbga' is not a valid color name
Traceback (most recent call last):
  File "/usr/lib/system76-driver/system76-firmware-dialog", line 504, in do_activate
    self.window = FirmwareWindow(self.data)
  File "/usr/lib/system76-driver/system76-firmware-dialog", line 254, in __init__
    self.create_notification_ui(data, thelio_io)
  File "/usr/lib/system76-driver/system76-firmware-dialog", line 294, in create_notification_ui
    changes = get_changes(data, markup=True)
  File "/usr/lib/system76-driver/system76-firmware-dialog", line 560, in get_changes
    changes_list = get_changes_list(data)
  File "/usr/lib/system76-driver/system76-firmware-dialog", line 533, in get_changes_list
    found[component] = not current[component]
NameError: name 'found' is not defined
```

**Comment by mmstick** [comment]
Nevermind, it's working now with the recent push.

**Comment by jackpot51** [comment]
I fixed that specific error, thanks for checking the later commit

**Comment by brs17** [comment]
Screenshots:

Screenshot from 2019-06-19 08-17-30

Screenshot from 2019-06-19 08-18-28

Selecting "Show Details" (one io board installed):
Screenshot from 2019-06-19 08-18-37

Selecting "Show Details" (two io boards installed):
Screenshot from 2019-06-19 08-57-52

**Comment by brs17** [comment]
Upon selecting `Install Firmware` the dialog disappears. Examining journald logs it appears to update successfully (although there is no specific success log message). I think the window should remain until the upgrade is complete and state a successful upgrade.

**Comment by mmstick** [comment]
When attempting to install Thelio I/O firmware, I'm getting this error, after the dialog disappears for a second:

```
2019-06-19 15:19:10,463  ERROR  Error calling _run_firmware_updater()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/system76driver/firmware.py", line 533, in run_firmware_updater
    ret = _run_firmware_updater(reinstall, notification, thelio_io)
  File "/usr/lib/python3/dist-packages/system76driver/firmware.py", line 475, in _run_firmware_updater
    iface.ThelioIoUpdate(digest)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Failed: Connection timed out (os error 110)
```

**Comment by mmstick** [comment]
System logs during the operation:

```
Jun 19 15:22:35 pop-os system76-firmware-daemon[14520]: ThelioIoDownload
Jun 19 15:22:35 pop-os system76-firmware-daemon[14520]: downloading manifest.json
Jun 19 15:22:35 pop-os system76-firmware-daemon[14520]: downloading metadata.json
Jun 19 15:22:35 pop-os system76-firmware-daemon[14520]: downloading main.hex
Jun 19 15:22:35 pop-os system76-firmware-daemon[14520]: ThelioIoList
Jun 19 15:22:36 pop-os kernel: usb 1-12: io_dev_revision failed: 110: io_dev_read
Jun 19 15:22:38 pop-os system76-firmware-daemon[14520]: ThelioIoUpdate(VF6M5O7Y6XRR7DFNBMZ7DOOK3XFKZRDTCZBZVI4WQIK5FUYRIZYRBJMZ7TLM3FRMYS3WHBGCYXUGM)
Jun 19 15:22:38 pop-os system76-firmware-daemon[14520]: Switching devices to bootloader
Jun 19 15:22:38 pop-os system76-firmware-daemon[14520]:  "/sys/bus/usb/devices/1-12"
Jun 19 15:22:39 pop-os system76-firmware-daemon[14520]:   revision: ""
Jun 19 15:22:39 pop-os system76-firmware-daemon[14520]:   switching to bootloader
Jun 19 15:22:39 pop-os kernel: usb 1-12: io_dev_revision failed: 110: io_dev_read
Jun 19 15:22:40 pop-os system76-firmware-daemon[14520]: Connection timed out (os error 110)
Jun 19 15:22:40 pop-os kernel: usb 1-12: io_dev_boot failed: 110: io_dev_read
```

**Pull request merged**
